### ISSUE TITLE
Not work for me, help please!

### ISSUE THREAD

**Issue by JB1985** [syseleven/nextcloud-tools#1]
Hello, 

I tried to decrypt my nextcloud, but no luck. There are some files that can not be decrypted. 

I have try your script but now work. I have edit the lines:

        // nextcloud definitions - you can get these values from config/config.php
        define("DATADIRECTORY", "/var/www/data");
        define("INSTANCEID",    "ocXXXXXXXXXX");
        define("SECRET",        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");

        // custom definitions
        define("DEBUGLEVEL",        DEBUG_DEFAULT);
        define("KEYTYPE",           KEY_MASTER);
        define("RECOVERY_PASSWORD", "");
        define("USER_NAME",         "");
        define("USER_PASSWORD",     "");

then i have try:

/tmp/decrypt-file.php /var/www/data/1171/files/cryptetfile.jpg

I get as output many funny symbols.

Any idea?

**Comment by yahesh** [comment]
@JB1985 Getting "funny symbols" when decrypting a JPEG file isn't unusual, as this is a binary-encoded file format. Try piping the output of the `decrypt-file.php` command into another file and see whether you can open the decrypted file afterwards:

```
/tmp/decrypt-file.php /var/www/data/1171/files/cryptetfile.jpg >/tmp/decryptedfile.jpg
```

**Comment by JB1985** [comment]
Yes sure, you are right! Thanks a lot for the script!
