### ISSUE TITLE
Problem with Decrypting: Secret key unavailable

### ISSUE THREAD

**Issue by JonnyTischbein** [syseleven/nextcloud-tools#10]
Hi,
I'm using a nextcloud 19.0.3 with `PHP 7.3.27-9+0~20210227.82+debian10~1.gbpa4a3d6 (cli)` and having still enabled the encryption module using the password recovery function. Since this feature brings a lot of problems I do want to deactivate it.

I set up the data directory, instance ID, secret (from the config.php) and the recovery password. 

But for every file I get the followering error:  `DEBUG: secretkey = unavailable`
```
        // nextcloud definitions - you can get these values from config/config.php
        define("DATADIRECTORY", "/var/www/nextcloud/data");
        define("INSTANCEID",    "xxxxxxxxxxxxxxxxx");
        define("SECRET",        "xxxxxxxxxxxxxxxxx");

        // recovery password definition
        define("RECOVERY_PASSWORD", "xxxxxxxxxxxxxxxxx");
```

```
DEBUG: filename = /var/www/nextcloud/data/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/files/Documents/Example.md
DEBUG: datafilename = Documents/Example.md
DEBUG: istrashbin = false
DEBUG: username = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx
DEBUG: filekey = /var/www/nextcloud/data/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/files_encryption/keys/files/Documents/Example.md/OC_DEFAULT_MODULE/fileKey
DEBUG: isencrypted = true
DEBUG: secretkey = unavailable
DEBUG: skipping this file...
DEBUG: success = false
```

Can you help me ?

*Edit*: also tested with `PHP 7.4.16 (cli)`

**Comment by yahesh** [comment]
@JonnyTischbein First question I have is this: Did every user activate the recovery feature? Activating the recovery feature is a two-step-process. First, the admin has to enable the feature and set the recovery password. But in in second step, each individual user has to activate that feature. It is **not** turned on for all users by default. From the debug information you provided it seems that the files are not encrypted for the recovery key.

**Comment by JonnyTischbein** [comment]
Thanks for your reply!

Yes. I have done that and I am also able to change password using the recovery feature or just tested use the internal nextcloud occ function to decrypt files for one user `sudo -u www-data php occ encryption:decrypt-all -vvv my-user-name`.

**Comment by yahesh** [comment]
@JonnyTischbein Ok, I extended the debug log a bit to print out which private keys have been loaded successfully. Please have a look if the private key for `recoveryKey_$random` is decrypted and then have a look if you can find corresponding `recoveryKey_$random.shareKey` files in your data directories.

**Comment by JonnyTischbein** [comment]
thank you for your effort! :)

That is definitely a problem. There are a lot of recovery keys, but they are not loaded.

```
$> find data -name "recovery*" | grep -oP "\/[a-zA-Z0-9_]+.shareKey$" |  sort | uniq -c  | while read -r a b; do echo "$b" "$a"; done
/recovery_454d6396.shareKey 4892

$> less decrypt.log | grep "private key for"
DEBUG: loaded private key for master_312ea844
DEBUG: loaded private key for master_b0f59ea0
DEBUG: loaded private key for pubShare_742e7751
DEBUG: loaded private key for pubShare_e1fa797d
```

The structure is e.g.
`data/[USER]/files_encryption/keys/files/folder/file.ext/OC_DEFAULT_MODULE/recovery_454d6396.shareKey`

**Comment by yahesh** [comment]
@JonnyTischbein Hm, I guess I see what the problem is there. Normally the recovery key is called `recoveryKey_$random` but for whatever reasons yours is just called `recovery_$random` which does not match the corresponding RegeEx to identify a recovery key. I modified the regex within the `decrypt-all-files.php` script now to match `recovery_$random` as well as `recoveryKey_$random`. Could you have another go and check whether the private key for `recovery_454d6396` is loaded sucessfully now?

**Comment by JonnyTischbein** [comment]
Thank you very very much!
Now it is working :)

Unfortunately the generation/including of the recovery key did not worked successfully for all files on all accounts. On some files it just misses.
Do you have any idea how I can fix this ?

**Comment by yahesh** [comment]
> Unfortunately the generation/including of the recovery key did not worked successfully for all files on all accounts. On some files it just misses.
> Do you have any idea how I can fix this ?

Unfortunately, I don't really understand what you mean by that. Does that mean that the recovery key has not been used for all files even though it has been activated by all users? Or does that mean that a  `recovery_454d6396.shareKey` file exists for files but they can still not be decrypted?

In general, your loaded private keys look a bit weird. Normally you would only have one master key and one pubShare key, but you seem to have two of them, as if you initialized the master-key-encryption twice at some point. Furthermore, with the master-key-encryption active, you normally wouldn't need the recovery key at all because all files would be encrypted with that central key. Unless, of course, you switched betweed master-key-encryption and user-key-encryption somewhere in between so that you've got a mixed setup.

**Comment by JonnyTischbein** [comment]
Yes, that setup is messed up. I have taken responsibility for the server and finally try to fix it.
The documentation is kind of lost. Because of that, I do not know it someone tried to switch the encryption type.
My goal is to complete disable this feature, because I do only have troubles with the user-key encryption and do not see a good reason to store it encrypted with a master key (beacuse the key has to be stored on the server).

But currently definetely the user-key-encryption is active.

For example one account: (and happens to 2-3 more)
Arround half of the files do have the recovery key and are decryptable. The other half only has 
```
$> ll data/user/files_encryption/keys/files/folder/file.ext/OC_DEFAULT_MODULE/
insgesamt 16
drwxr-xr-x 2 www-data www-data 4096 Nov 14  2017 .
drwxr-xr-x 3 www-data www-data 4096 Nov 14  2017 ..
-rw-r--r-- 1 www-data www-data   44 Nov 14  2017 fileKey
-rw-r--r-- 1 www-data www-data  512 Nov 14  2017 user.shareKey
```

I already ask the user to re-enable the password recovery and hope that this will generate the key for all files.

**Comment by JonnyTischbein** [comment]
Short update:
For some users deactivating and activating again the recovery key worked.

One user can't reenable the recovery key. But no logs on the server side.
```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    <anonymous> settings-personal.js:43
```
settings-personal.js
````
	// Trigger ajax
on recoveryAdmin status change
	$('input:radio[name="userEnableRecovery"]').change(
		function () {
			var recoveryStatus = $(this).val();
			OC.msg.startAction('#userEnableRecovery .msg', 'Updating recovery keys. This can take some time...');
			$.post(
				OC.generateUrl('/apps/encryption/ajax/userSetRecovery'),
				{
					userEnableRecovery: recoveryStatus
				}
			).done(function (data) {
					OC.msg.finishedSuccess('#userEnableRecovery .msg', data.data.message);
				})
				.fail(function (jqXHR) {
43:					OC.msg.finishedError('#userEnableRecovery .msg', JSON.parse(jqXHR.responseText).data.message);
				});
			// Ensure page is not reloaded on form submit
			return false;
		}
	);
```

In that special case it is toleratable if no others are effected.
But I guess from here on I have to reach out to the nextcloud developers right ? (It is hard to get any response there)

**Comment by yahesh** [comment]
> Yes, that setup is messed up. I have taken responsibility for the server and finally try to fix it.
> The documentation is kind of lost. Because of that, I do not know if someone tried to switch the encryption type.

I don't envy you for this task.

> In that special case it is toleratable if no others are effected.
> But I guess from here on I have to reach out to the nextcloud developers right ? (It is hard to get any response there)

If it is really just one user where re-activating the recovery feature doesn't work, one might be tempted to ask this single user to provide their password and let them change their password after the decryption is done (the `decrypt-all-files.php` script support user-key-encryption as well, if you have a user called `exampleuser` you would set the corresponding password via `define("USER_PASSWORD_EXAMPLEUSER", "V3RY 57R0NG P455W0RD");`).

**Comment by JonnyTischbein** [comment]
Is there some way to only decrypt one single user/folder implemented ?

**Comment by yahesh** [comment]
@JonnyTischbein Not in an easy-to-use way. But it should not be too difficult to implement.

**Comment by yahesh** [comment]
@JonnyTischbein You could have a go with the newest version which introduces the optional `userdir` parameter. If you provide the name of the corresponding user as a second parameter, the script should only decrypt the files of that user.
```
./decrypt-all-files.php <targetdir> [<userdir>]
```

**Comment by JonnyTischbein** [comment]
Wow! I love it! A thousand thanks to you :)

**Comment by yahesh** [comment]
The script has now been further improved so that it's also possible to decrypt single files.

I guess this issue is done?

**Comment by JonnyTischbein** [comment]
Yes!
Thanks a lot again! :)
