### ISSUE TITLE
Targetdir not given or does not exist

### ISSUE THREAD

**Issue by Llazcanoster** [syseleven/nextcloud-tools#11]
Hi, I am using Nextcloud 21.0.1 with PHP 7.4.18 and after configuring the decrypt-all-files.php parameters (data directory, instance ID, secret, etc), I think it is correct, and run as root: ./decrypt-all-files.php /path/to/folder/created/and/empty/ username, I get the following output:

DEBUG: debug mode enabled
ERROR: TARGETDIR NOT GIVEN OR DOES NOT EXIST

What have I not understood or something that I am overlooking?

Thanks for the great work

**Comment by Eeems** [comment]
https://github.com/syseleven/nextcloud-tools/blob/master/rescue/decrypt-all-files.php#L729

Are you sure the directory exists and is reachable by your php configuration (open_basedir setting)?

**Comment by yahesh** [comment]
@Llazcanoster It would be ideal to see what you actually tried to execute. Unfortunately,  Maybe your target directory contains a space character which would cause the path to be broken into two parts or something else might have happend that I can't see from the provided information. :)

**Comment by Llazcanoster** [comment]
https://github.com/syseleven/nextcloud-tools/issues/11#issuecomment-845198675

Yes, the directory exists and is reachable and regarding open_basedir, it is not set, anyway I have tried within several locations, even in the server's Nextcloud path, do you think that not having this variable set may be what causes the problem?

**Comment by Llazcanoster** [comment]
https://github.com/syseleven/nextcloud-tools/issues/11#issuecomment-845450041

Hi!! The sentence entered is:

./decrypt-all-files.php/home/xxxx/rescuef/ xxxxxx-xxx-xxxxx-xxxx-xxxxxx
I have also tried:
php decrypt-all-files.php /home ...

**Comment by yahesh** [comment]
@Llazcanoster As already noted by @Eeems, the script does a simple `is_dir()` check on the provided target path. This folder has to exist and be empty. There really isn't much more that I could suggest than for you to double- and tripple-check that the provided targetdir exists and is accessible by the user you're using to execute the script.

**Comment by Llazcanoster** [comment]
@yahesh Some very silly mistake I must be making, but it's breaking my head :)))
I will continue investigating

Thanks

**Comment by w1ld3r** [comment]
I've created a pull request to resolve this issue. Tested and working fine. #12

**Comment by yahesh** [comment]
@w1ld3r Thanks for the fix. What a not-so-intelligent logic error. 😅

@Llazcanoster You could have another try.

**Comment by w1ld3r** [comment]
A funny one ;)

**Comment by Llazcanoster** [comment]
Now is working perfectly!! I have managed to recover many directories of users "little cautious"
Thanks to @yahesh , @w1ld3r , @Eeems , @baurmatt 

Again thank you very much for the work

**Comment by yahesh** [comment]
@Llazcanoster Good to hear that the script was helpful. Will close this ticket then. :)
