### ISSUE TITLE
some files do not get decrypted

### ISSUE THREAD

**Issue by celevra** [syseleven/nextcloud-tools#15]
Hi,

we are on NextCloud Docker 21 and had problems deactivating server side enryption
it does tell us that the server side encryption isn't enabled so i'm forced to encrypt by hand.
That worked quite good with decrypt-all but there are some files (a few thousand) that won't get decrypted

```
DEBUG: filename = /var/www/html/data/restore/data/pascal/files/Privat/Pascal/Persönliche Unterlagen/Immobilien/Zerzabelshoferstr. 31, Nürnberg/z.pdf
DEBUG: datafilename = Privat/Pascal/Persönliche Unterlagen/Immobilien/Zerzabelshoferstr. 31, Nürnberg/z.pdf
DEBUG: istrashbin = false
DEBUG: username = pascal
DEBUG: filekeyname = /var/www/html/data/restore/data/pascal/files_encryption/keys/files/Privat/Pascal/Persönliche Unterlagen/Immobilien/Zerzabelshoferstr. 31, Nürnberg/z.pdf/OC_DEFAULT_MODULE/fileKey
DEBUG: isencrypted = true
DEBUG: sharekeyname = /var/www/html/data/restore/data/pascal/files_encryption/keys/files/Privat/Pascal/Persönliche Unterlagen/Immobilien/Zerzabelshoferstr. 31, Nürnberg/z.pdf/OC_DEFAULT_MODULE/master_442d4d04.shareKey

Warning: openssl_decrypt(): IV passed is 32 bytes long which is longer than the 16 expected by selected cipher, truncating in /var/www/html/data/nextcloud-tools/rescue/decrypt-all-files.php on line 157

Warning: openssl_decrypt(): IV passed is 32 bytes long which is longer than the 16 expected by selected cipher, truncating in /var/www/html/data/nextcloud-tools/rescue/decrypt-all-files.php on line 157
DEBUG: secretkey could not be decrypted
DEBUG: secretkey = unavailable
DEBUG: skipping this file...
DEBUG: success = false
ERROR: /var/www/html/data/restore/data/pascal/files/Privat/Pascal/Persönliche Unterlagen/Immobilien/Zerzabelshoferstr. 31, Nürnberg/z.pdf FAILED
```

so to dig deeper i tried it with decrypt-file.php

this is the result:
```
www-data@c4e2b4bbe624:~/html/data/nextcloud-tools/debug$ php decrypt-file.php 'pascal/files/Privat/Pascal/Pers\303\266nliche Unterlagen/Immobilien/Zerzabelshoferstr. 31, N\303\274rnberg/z.pdf'
Warning: openssl_open(): unable to coerce parameter 4 into a private key in /var/www/html/data/nextcloud-tools/debug/decrypt-file.php on line 391
/var/www/html/data/restore/data/pascal/files/Privat/Pascal/Persönliche Unterlagen/Immobilien/Zerzabelshoferstr. 31, Nürnberg/z.pdf: File not decrypted.

www-data@c4e2b4bbe624:~/html/data/nextcloud-tools/debug$ file '/var/www/html/data/restore/data/pascal/files/Privat/Pascal/Pers\303\266nliche Unterlagen/Immobilien/Zerzabelshoferstr. 31, N\303\274rnberg/z.pdf'                               /var/www/html/data/restore/data/pascal/files/Privat/Pascal/Persönliche Unterlagen/Immobilien/Zerzabelshoferstr. 31, Nürnberg/z.pdf: data


www-data@c4e2b4bbe624:~/html/data/restore/data/pascal/files_encryption/keys/files/Privat/Pascal/Persönliche Unterlagen/Immobilien/Zerzabelshoferstr. 31, Nürnberg/z.pdf/OC_DEFAULT_MODULE$ ls -alh
total 16K
drwxr-xr-x 2 www-data www-data 4.0K Jun 21 06:47 .
drwxr-xr-x 3 www-data www-data 4.0K Jun 14 10:17 ..
-rw-r--r-- 1 www-data www-data  292 Jun 14 10:17 fileKey
-rw-r--r-- 1 www-data www-data 1.6K Jun 14 10:17 master_442d4d04.shareKey
www-data@c4e2b4bbe624:~/html/data/restore/data/pascal/files_encryption/keys/files/Privat/Pascal/Persönliche Unterlagen/Immobilien/Zerzabelshoferstr. 31, Nürnberg/z.pdf/OC_DEFAULT_MODULE$
```

is there anything i can provide to dig deeper into the Problem?

thank you in advance for your help

**Comment by yahesh** [comment]
@celevra Unfortunately, the `decrypt-file.php` debug script currently isn't up-to-date. It only supports Nextcloud 19, while the `decrypt-all-files.php` is currently tested against Nextcloud 19 and 20.

The error message _"IV passed is 32 bytes long which is longer than the 16 expected by selected cipher, truncating in /var/www/html/data/nextcloud-tools/rescue/decrypt-all-files.php on line 157"_ is quite interesting. Maybe something has changed in the encryption again.

Do you see if the files that fail to be decrypted have been changed (and thus been re-encrypted) recently?

**Comment by celevra** [comment]
The file is from 14th July, if you want to I can send you a test file and the keys

**Comment by yahesh** [comment]
@celevra Would be excellent.

**Comment by yahesh** [comment]
I think I've found the culprit. As it seems, the Nextcloud devs have introduced a new wrapper-encryption scheme v3 that currently isn't supported: https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/lib/private/Security/Crypto.php#L136-L140

Shouldn't be too much effort to introduce it as well.

**Comment by celevra** [comment]
Looking forward to, thank your for your work!

**Comment by celevra** [comment]
```
        define("INSTANCEID",    "ocvwqvd3ofgn");
        define("SECRET",        "Sh5J8CVYYvgwFgu5f0NARqcF1JRQ8jXjKK8P9wbNe64knxhB");
```
[Expose.pdf](https://github.com/syseleven/nextcloud-tools/files/6703866/Expose.pdf)
[master_442d4d04.shareKey.txt](https://github.com/syseleven/nextcloud-tools/files/6703869/master_442d4d04.shareKey.txt)
[fileKey.txt](https://github.com/syseleven/nextcloud-tools/files/6703870/fileKey.txt)

**Comment by yahesh** [comment]
Removed your last comment as it contains information that should not be public. I've seen what I needed to see which is that - indeed - your encryption keys are wrapped with the new v3 encryption which needs to be implemented.

**Comment by celevra** [comment]
I'm sure you are very busy and we appreciate your work
What do you think how long will it take until the new encryption is embedded in your tool?

**Comment by yahesh** [comment]
My schedule is pretty much packed till saturday. Will probably have time to look at it after that.

**Comment by celevra** [comment]
Thank you for the timeline

**Comment by celevra** [comment]
So to stress you, any news on this? Is there anything I can do?

**Comment by yahesh** [comment]
@celevra It took a bit longer but now the newest version is online. It also supports resumes, has improved support for external storage and it is now possible to decrypt individual files as well as specific sub-folders.

**Comment by celevra** [comment]
that worked like a charm! Now all 56.000 Files decrypted successfully
is there a way to send you a beer?

**Comment by yahesh** [comment]
@celevra Good to here that the added support for the v3 wrapper encryption solved your problem. :)

I'll enjoy a cool Bananenweizen this evening to celebrate the success. 🍻
