### ISSUE TITLE
trashed version files in subfolders - skipping this file...

### ISSUE THREAD

**Issue by chainria** [syseleven/nextcloud-tools#17]
Firstly, I wanted to give you all a HUGE thanks to this toolkit, since NC can't decrypt versioned/trashed/trashed versioned files at all (which is actually far more important to me than the current files).

However, I stumble upon a strange problem. I have some files which it is skipping over, they have the following layout:

<username>/files_trashbin/versions/<folderstructure>.v[0-9]+/<filename>.d<deletetime>\.d[0-9]+

Once such example would be:

DEBUG: filename = /mnt/nas01.rich/home/nextcloud/chain/files_trashbin/versions/Isis.d1599728890/simon-eckert-by-simon-eckert-smite-isis-characters-fantasy-g.jpg.v1592172693

One more complicated is this one:

DEBUG: filename = /mnt/nas01.rich/home/nextcloud/chain/files_trashbin/versions/Paradise.d1589620788/Kikara/75wyqm4p.jpg.v1499580258

So it seems the main folder has the deletion date, but the files themselves nested have the version date. I don't know where exactly this structure comes from, maybe some old version of NC/OC? Or is something weird on my file tree? Any pointers on how to properly handle these files (maybe some elseif for L678?) would be greatly appreciated!

**Comment by yahesh** [comment]
@chainria I know, it took quite a while but I finally came around to implementing support for versions of encrypted files that are stored in trashbin subfolders (see https://github.com/syseleven/nextcloud-tools/commit/b3846dfaf4ec77ddd15b42e2e5b58d86a73995fc). I tested this with multiple levels of subfolders.
