### ISSUE TITLE
How to set up these scripts?

### ISSUE THREAD

**Issue by anLizard** [syseleven/nextcloud-tools#2]
Hi, I found this repository while researching decryption in nextcloud.
Sadly I am a total noob when it comes to php, so I have absolutely no clue how to use these scripts. I need to decrypt some files I have hosted.

I have Nextcloud and mariadb running in docker containers, and have a backup of my encryption keys.
Where do I begin? Do I just host the php file on a php server, open the url for it and look where to go from there? Please help, I have a few thousand files I need to recover.

**Comment by yahesh** [comment]
@anLizard Hi there, the scripts in this repository have to be used from the command line. On a Linux system system this will often require you to install a package called `php-cli`.

Decrypting files is done through the script [decrypt-file.php](https://raw.githubusercontent.com/syseleven/nextcloud-tools/master/decrypt-file.php). All scripts are self-contained, which means that if you have the PHP command-line interface installed, have configured the script (according to the corresponding [README section](https://github.com/syseleven/nextcloud-tools/blob/master/README.md#decrypt-filephp)) and the script has access to your data directory (that has to be set as the `DATADIRECTORY` configuration value) then you can use the script as described in the usage example: `php ./decrypt-file.php <filename>` (whereby you have to replace `<filename>` with the name of the file you want to decrypt). The script will then output the decrypted file contents to STDOUT and you will have to pipe the output to some target file.

**Comment by anLizard** [comment]
Many thanks for your detailed explanation! I'm going to give this a go soon, thanks a lot!

**Comment by anLizard** [comment]
I set up the script and path but upon running `sudo php decrypt-file.php <PATH TO FILE>`
I get the error "Key is not a file."

Tried it with both Master and user mode.

**Comment by yahesh** [comment]
@anLizard The `Key is not a file.`Key is not a file.` error message indicates that the file that the keyfile relating to the chosen file-to-be-decrypted could not be found. Could you try to provide the filename of the file-to-be-decrypted relative to the `DATADIRECTORY` path? To decrypt the files you will need access to the whole data directory of your Nextcloud installation.

**Comment by unclesamwk** [comment]
Can you help me please ...

**Comment by anLizard** [comment]
Hi, sorry for replying so late. Did not have the time to get around to actually getting this done.

I started over and backed up my entire data folder to a local Windows machine and now have my decrypt-file.php set up like this:
```
	define("DATADIRECTORY", "");
	define("INSTANCEID",    "redacted");
	define("SECRET",        "redacted");
```

`DATADIRECTORY ` was set to blank because I intend to use an absolute path when I execute the command:
```
php .\decrypt-file.php "D:\data\user\files\image.PNG"
D:\data\user\files\image.PNG: File has unknown filename format.
```

I also tried setting `DATADIRECTORY ` to my local data path
	define("DATADIRECTORY", "D:\data");
	define("INSTANCEID",    "redacted");
	define("SECRET",        "redacted");

But it results in the same error:
```
php .\decrypt-file.php user\files\image.PNG
D:\data/user\files\image.PNG: File has unknown filename format.
```

Could this be because I am on windows and it uses backslash instead of slash?
This is what happens if I replace the slashes with back slash in `DATADIRECTORY `and when executing:
```
php ./decrypt-file.php tobias/files/Backup/Tobias_PhotoBackup/cursed.PNG
D:/Stuff/Nextcloud Photos Encrypted/data/tobias/files/Backup/Tobias_PhotoBackup/cursed.PNG: Key is not a file.
```

I double checked and can confirm that the `fileKey` and `master_gibberish.shareKey` files are present for the file I am trying to decrypt.

**Comment by yahesh** [comment]
@anLizard Ah, that's important to know. This script has only been tested on Linux. I actually don't have a M$ system on hand to test it on Windows. It's a good sign that you get the different "Key is not a file." message when writing the file name with slashes instead of backslashes. That means that the RegEx within `main()` passed.

What you could do is change line 435 into:
```
var_dump($keyfilename);
```

You could also change line 447 into:
```
var_dump($filekeyfilename); var_dump($sharekeyfilename);
```

Sorry, that we have to debug through this remotely.

**Comment by anLizard** [comment]
@yahesh thanks so much for helping me through this still, even if it is through remote debugging.

I changed the lines like you suggested, but unfortunatly still got the same results, so I decided to move it to my Linux machine instead and work from there.

I downloaded your script again for a fresh start and reinserted my nextcloud/custom definitions, but still get the "Key is not a file." error with both the relative path to the data folder, and the absolute path.

**Comment by yahesh** [comment]
@anLizard Have you checked the output of the `var_dump()` calls? Do all of these files exist?

**Comment by anLizard** [comment]
With KEY_USER:
`me@host:~$ php ./decrypt-file.php ~/data/user/files/path/image.png
string(114) "~/data/user/files_encryption/OC_DEFAULT_MODULE/user.privateKey"
string(152) "~/data/user/files_encryption/keys/files/path/image.png/OC_DEFAULT_MODULE/fileKey"
string(160) "~/data/user/files_encryption/keys/files/path/image.png/OC_DEFAULT_MODULE/user.shareKey"
~/data/user/files/path/image.png: Key is not a file.
`

With KEY_MASTER:
`
me@host:~$ php ./decrypt-file.php ~/data/user/files/path/image.png
PHP Warning:  scandir(~/data/files_encryption/OC_DEFAULT_MODULE/): failed to open dir: No such file or directory in /home/tobias/Downloads/Nextcloud_Photos_Encrypted/decrypt-file.php on line 328
PHP Warning:  scandir(): (errno 2): No such file or directory in /home/me/decrypt-file.php on line 328
PHP Warning:  Invalid argument supplied for foreach() in /home/me/decrypt-file.php on line 329
~/data/user/files/path/image.png: Key ID could not be retrieved.
`

I found out that the directory`~/data/user/files_encryption/OC_DEFAULT_MODULE/`
is not present.

My active Nextcloud instance has some encrypted files on it that I can access just fine, but it also does not have the `files_encryption/OC_DEFAULT_MODULE/` folder.

I am not very familiar with php, so I hope this is the correct info.

**Comment by anLizard** [comment]
Update: I recovered the folder with OC_DEFAULT_MODULE folder with the files
```
master_xxxxxxx.privateKey
pubShare_xxxxxxxx.privateKey
master_xxxxxxxx.publicKey
pubShare_xxxxxxxx.publicKey
```

But I am still getting the same errors

**Comment by yahesh** [comment]
When you only have the `master_*` and `pubShare_*` files that means that the `KEY_MASTER` configuration is the correct one for you. I'm a bit astounded that you get the same error messages when setting the `"KEYTYPE"` configuration correctly, as you should have created the `~/data/files_encryption/OC_DEFAULT_MODULE/` folder when you recovered the `OC_DEFAULT_MODULE` folder.

**Comment by anLizard** [comment]
Turns out I recovered the folder to the wrong directory, so sorry about my previous comment.

I tried again this afternoon after double checking the path and am happy to report it decrypts my files correctly! Thank you SO MUCH for your work on this script and all your help, you helped me recover almost 60 GB of data!

**Comment by yahesh** [comment]
@anLizard I hope, you though about removing the `var_dump()` calls again.

Other than that, I'm happy that it worked for you. :)

**Comment by anLizard** [comment]
Yep, noticed they needed to be removed and managed to successfully decrypt!
Now I just need to write a little bash script to have it execute for all the files and everything is golden :D

**Comment by yahesh** [comment]
@anLizard If this should still be an issue for you: Maybe you noticed that there is now a `rescue/decrypt-all-files.php` script so that people don't have to loop over the files themselves anymore. :)
