### ISSUE TITLE
decrypt-all-files.php is not able to decrypt the file

### ISSUE THREAD

**Issue by vagner-dias** [syseleven/nextcloud-tools#20]
Hi, @yahesh ,

I tried to execute the decrypt-all-files.php script but the script is triggering the "not able to decrypt the file" error.

My instance: Nextcloud 21.0.7

Here is the debug print:
root@recupera-crash:/var/www/nextcloud# sudo -u www-data php decrypt-all-files.php "/recovery/" "/appdata/drive/data/XXXXX/files/Pessoal/BankTransfer-1.pdf"
DEBUG: debug mode enabled
DEBUG: loaded private key for master_846b3b7c
DEBUG: loaded private key for pubShare_846b3b7c
DEBUG: filename = /appdata/drive/data/XXXXX/files/Pessoal/BankTransfer-1.pdf
DEBUG: target = /recovery/XXXXX/files/Pessoal/BankTransfer-1.pdf
DEBUG: datafilename = Pessoal/BankTransfer-1.pdf
DEBUG: istrashbin = false
DEBUG: username = XXXXX
DEBUG: filekeyname = /appdata/drive/data/XXXXX/files_encryption/keys/files/Pessoal/BankTransfer-1.pdf/OC_DEFAULT_MODULE/fileKey
DEBUG: isencrypted = true
DEBUG: sharekeyname = /appdata/drive/data/XXXXX/files_encryption/keys/files/Pessoal/BankTransfer-1.pdf/OC_DEFAULT_MODULE/master_846b3b7c.shareKey
DEBUG: secretkey could not be decrypted
DEBUG: secretkey = unavailable
DEBUG: cannot decrypt this file...
DEBUG: success = false
ERROR: /appdata/drive/data/XXXXX/files/Pessoal/BankTransfer-1.pdf FAILED
DEBUG: exiting

I have already checked the fileKey, master_846b3b7c.shareKey, master_846b3b7c, and pubShare_846b3b7c files. All of them are on their places with the keys, however, I am sill not able to decrypt them.

Can you shred some light as to what I am doing wrong here? I am lost.

**Comment by yahesh** [comment]
@vagner-dias Sorry for editing your message, but I wanted to make sure that it does not contain actual file contents or valid e-mail addresses of users. I tried to decrypt the provided file and it breaks [here](https://github.com/syseleven/nextcloud-tools/blob/master/rescue/decrypt-all-files.php#L727). Until there everything works as expected, which means that either the shareKey, the fileKey or the master_846b3b7c private key do not belong to each other. As `openssl_open()` is an `openssl_private_decrypt()` with RSA followed by an `openssl_decrypt()` with RC4, I tried to decrypt the file key by hand:
```
if (!openssl_private_decrypt($sharekey, $plainkey, $privatekeys[$key], OPENSSL_PKCS1_PADDING)) {
  debug("rsa decryption failed");
} else {
  debug("sharekey = ".bin2hex($plainkey));

  $filekey = openssl_decrypt($filekey, "rc4", $plainkey, OPENSSL_RAW_DATA);
  if (false === $filekey) {
    debug("rc4 decryption failed");
  } else {
    debug("filekey  = ".bin2hex($filekey));
  }
}
```

However, it is the RSA decryption that fails, from which I assume that the master_846b3b7c private key does not belong to the sharekey on disk. Therefore, some questions arise:
* Is this the only file that fails to decrypt?
* What is the history of your Nextcloud instance?
* Is it possible that the primary key has been re-generated some time in the past?

**Comment by vagner-dias** [comment]
@yahesh, I´ve just found what happened. The latest and the second latest encryption keys were not working but now I tested a version of the encryption key before those 2 versions and now I am decrypting the 10k+ files I had lost.

Thank you so much for creatin this awsome tool! You are a life saviour!! 💯 :-)

**Comment by yahesh** [comment]
@vagner-dias I'm happy to hear that you were able to recover the original key files and to recover your files successfully. The file versioning of S3 really came in handy here. :)
