### ISSUE TITLE
Unable to decrypt files with decrypt-all-files.php

### ISSUE THREAD

**Issue by matteo-nini** [syseleven/nextcloud-tools#21]
Hey there!

I've set the correct data for DATADIRECTORY, INSTANCEID and SECRET variables, then, i tried to execute the decrypt-all-files.php script but for some files it give me this message:
ERROR: path/to/file FALIED

Is there some solution for this?

**Comment by yahesh** [comment]
@matteo-nini Given that this only affects some of your files, I'd assume that it has to do with some changes that happened to your setup that broke keys or similiar. You could enable the debug mode by setting [this value](https://github.com/syseleven/nextcloud-tools/blob/master/rescue/decrypt-all-files.php#L95) to `true` and have a look at the details.

**Comment by matteo-nini** [comment]
> @matteo-nini Given that this only affects some of your files, I'd assume that it has to do with some changes that happened to your setup that broke keys or similiar. You could enable the debug mode by setting [this value](https://github.com/syseleven/nextcloud-tools/blob/master/rescue/decrypt-all-files.php#L95) to `true` and have a look at the details.

@yahesh i've run the script with `DEBUG_MODE` set as `true`.

```
DEBUG: filename = /home/srv/www/xyz/data/data/username/files_trashbin/files/filemane.pdf.d1649419441
DEBUG: target = /home/srv/www/upgrade.d/decryptedata4/username/filestrashbin/files/filename.pdf.d1649419441
DEBUG: datafilename = filename.pdf.d1649419441
DEBUG: istrashbin = true
DEBUG: username = username
DEBUG: secretkey = unavailable
DEBUG: trying to copy file...
DEBUG: success = false
```

there are also some strange things like:

```
DEBUG: filename = /home/srv/www/xyz/data/data/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/username/files_encryption/keys/files/path/to/file/OC_DEFAULT_MODULE/fileKey
DEBUG: target = /home/srv/www/upgrade.d/decryptedata4/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/username/files_encryption/keys/files/path/to/file/OC_DEFAULT_MODULE/fileKey
```

**Comment by yahesh** [comment]
@matteo-nini Could you please check the following things:

1. What does the start of the file `/home/srv/www/xyz/data/data/username/files_trashbin/files/filemane.pdf.d1649419441` look like? It seems as if the script is unable to find the corresponding filekey, then tries to copy the file unencrypted. To prevent encrypted files from being unnoticed, the unencrypted copy command peeks into the file and checks whether it contains the usual encryption header. If so, the unencrypted copy will fail. So I assume that the file is actually encrypted but you (somehow) lost the corresponding encryption filekey.

2.) Does the file `/home/srv/www/xyz/data/data/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/keys/username/files_encryption/keys/files/path/to/file/OC_DEFAULT_MODULE/fileKey` really exist on disk? If so then maybe that is where your encryption keys have gone and you may only have to copy or move them back to restore your files.

**Comment by Gattuso11** [comment]
> Hey there!
> 
> I've set the correct data for DATADIRECTORY, INSTANCEID and SECRET variables, then, i tried to execute the decrypt-all-files.php script but for some files it give me this message:
> ERROR: path/to/file FALIED
> 
> Is there some solution for this?

Try contact cluserver on Instagram who helped me out

**Comment by Gattuso11** [comment]
> @matteo-nini Given that this only affects some of your files, I'd assume that it has to do with some changes that happened to your setup that broke keys or similiar. You could enable the debug mode by setting [this value](https://github.com/syseleven/nextcloud-tools/blob/master/rescue/decrypt-all-files.php#L95) to `true` and have a look at the details.

Cluserver on Instagram can help you

**Comment by fastlorenzo** [comment]
You could try with the PR I just made to support legacy format, maybe those files were created previously and using it and other files were created after and using the new format (just making assumptions here) #24

**Comment by yahesh** [comment]
@matteo-nini The patch of @fastlorenzo is now part of the upstream version of the `decrypt-all-files.php` script. Maybe it helps in case your files are much older than Nextcloud 16.

**Comment by yahesh** [comment]
@matteo-nini Is this still an issue?

**Comment by yahesh** [comment]
@matteo-nini There has been a major overhaul of this script. Please have a look if it works for you.

**Comment by yahesh** [comment]
@matteo-nini Did you come around to testing the newest version of the script?
