### ISSUE TITLE
"secretkey could not be decrypted" on Nextcloud 24

### ISSUE THREAD

**Issue by Kevin8675** [syseleven/nextcloud-tools#25]
Hi there,

I am trying to use this script to decrypt my files but it ends up failing to decrypt the secret key:
```
DEBUG: filename = /home/USER/nextcloud/nextcloud/data/Kevin/files/files.md
DEBUG: target = /home/USER/Decrypted/Kevin/files/files.md
DEBUG: datafilename = files.md
DEBUG: istrashbin = false
DEBUG: username = Kevin
DEBUG: filekeyname = /home/USER/nextcloud/nextcloud/data/Kevin/files_encryption/keys/files/files.md/OC_DEFAULT_MODULE/fileKey
DEBUG: isencrypted = true
DEBUG: sharekeyname = /home/USER/nextcloud/nextcloud/data/Kevin/files_encryption/keys/files/files.md/OC_DEFAULT_MODULE/master_477067ac.shareKey
DEBUG: secretkey could not be decrypted
DEBUG: secretkey = unavailable
DEBUG: cannot decrypt this file...
DEBUG: success = false
ERROR: /home/USER/nextcloud/nextcloud/data/Kevin/files/files.md FAILED
DEBUG: filename = /home/USER/nextcloud/nextcloud/data/Kevin/files_encryption/keys/files/files.md/OC_DEFAULT_MODULE/fileKey
DEBUG: target = /home/USER/Decrypted/Kevin/files_encryption/keys/files/files.md/OC_DEFAULT_MODULE/fileKey
DEBUG: skipping this file...
```

I have also tried using this script on a brand new instance and it fails with the same error. Any help appreciated.

**Comment by yahesh** [comment]
I tried to setup a new Nextcloud 24 testing instance but failed with the usual VM installation script as the encryption module is not able to encrypt the test files. Will have to look into setting up a working instance through a different method.

**Comment by Kevin8675** [comment]
I was able to create a new instance with docker fairly easily.

**Comment by yahesh** [comment]
I used the Docker AIO image now and can actually reproduce the issue.

**Comment by yahesh** [comment]
@Kevin8675 Which operating system do you use to execute `./decrypt-all-files.php`? Could you especially provide the output of `openssl version`?

**Comment by yahesh** [comment]
It is not a problem with the `./decrypt-all-files.php` script but with the algorithm choice of Nextcloud. `openssl_open()` throws an `error:0308010C:digital envelope routines::unsupported` on systems that have OpenSSL v3 installed. There is a corresponding issue in the [Nextcloud Server issue tracker](https://github.com/nextcloud/server/issues/32003). That's probably also the reason why the server-side encryption in the newly set-up VM didn't work as I used Ubuntu 22.04 with OpenSSL v3 there as well.

@martb has [provided a work-around](https://github.com/nextcloud/server/issues/32003#issue-1206486960) in the Nextcloud issue. You can add the following configuration block to the end of your system's `openssl.cnf` file. For Ubuntu 22.04 this is located at `/usr/lib/ssl/openssl.cnf`:

```
[provider_sect]
default = default_sect
legacy = legacy_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1
```

**Comment by yahesh** [comment]
I added the corresponding description to the README.

**Comment by Kevin8675** [comment]
Wow, thanks so much! Your help just saved my hundreds of files! Thanks again!

**Comment by yahesh** [comment]
Nice to here that the solution worked for you. :)

**Comment by yahesh** [comment]
The `decrypt-all-files.php` script now contains its own RC4 implementation so that the OpenSSL v3 workaround is not necessary anymore.
