### ISSUE TITLE
Unable to decrypt files

### ISSUE THREAD

**Issue by pezlaf** [syseleven/nextcloud-tools#28]
Hello, 
I am trying to decrypt files since I am getting error messages on Nextcloud about the fact that end-to-end encryption module cannot be enabled due to some database migration error.

I tried decrypt-all-files.php, which seemed to work at first, however it simply copied the encrypted folders/files to the target directory (with the cryptic names), while files/folders that were unencrypted to begin with were also copied as is (unencrypted). 

I have provided DATADIRECTORY, INSTANCEID and SECRET in the configuration: am I missing anything else in the procedure?
Do I need to provide the mnemonic passphrase somewhere for decryption to work properly with this script? 

Thank you in advance for your help.

**Comment by yahesh** [comment]
@pezlaf Could you please enable the debug mode in the script and provide the debug output? You have to this in the script:

```
	// debug mode definition
	define("DEBUG_MODE", true);
```

**Comment by pezlaf** [comment]
sure,
thanks

**Comment by pezlaf** [comment]
github complains that my comment is too long.
I will try to split it.

**Comment by pezlaf** [comment]
I uploaded the console output file instead:

[debug_decrypt-all-files.txt](https://github.com/syseleven/nextcloud-tools/files/9944557/debug_decrypt-all-files.txt)

**Comment by yahesh** [comment]
@pezlaf Would you please use a new, empty target folder when creating the debug log? It's not possible to see a single decryption if all files are already in the target folder. :)

**Comment by pezlaf** [comment]
[debug_decrypt-all-files_v2.txt](https://github.com/syseleven/nextcloud-tools/files/10067665/debug_decrypt-all-files_v2.txt)

**Comment by yahesh** [comment]
@pezlaf The debug log looks fine so far. The Nextcloud Server Side Encryption does not encrypt file names. Are you sure that the contents of those files with the _"cryptic"_ file names is actually still encrypted?

**Comment by pezlaf** [comment]
Well, not all files are encrypted, only some folders/files are, and these are still encrypted.
I fear that the database has been corrupted, and because of that, Nextcloud's end-to-end encryption plugin does not work properly and was disabled (I get a database migration error message whenever I try to re-enable it in the settings).
I was looking for a way to bypass the encryption plugin and decrypt the few encrypted files that I have.
After that I would have re-installed the NextCloud server,

Don´t I need to provide the mnemonic passphrase somewhere in the config for your tool to be able to decrypt files?
I could not find info about that.

**Comment by pezlaf** [comment]
Just to be clear: the database corruption happened before using this tool...

**Comment by yahesh** [comment]
@pezlaf Are you currently running Nextcloud 25? It seems that it has introduced a binary file structure that the decryption script doesn't support yet. I will have to look into it.

**Comment by pezlaf** [comment]
I am using Nextcloud 24.0.7

**Comment by yahesh** [comment]
@pezlaf There has been a major overhaul of this script. Please have a look if it works for you.

**Comment by yahesh** [comment]
@pezlaf Did you come around to testing the newest version of the script?

**Comment by yahesh** [comment]
Closing this after a quarter without a response.
