### ISSUE TITLE
"File has unknown filename format" while trying to decrypt files from external storage

### ISSUE THREAD

**Issue by JonasOelke** [syseleven/nextcloud-tools#3]
Hey! 

at first many thanks for providing such helpful scripts to the world! 

What I am working on: I had external storage connected to my nextcloud (OneDrive to be specific). Luckily nextcloud just encrypted the files I already access (and not my whole OneDrive), because accessing onedrive from nextcloud is a pain (but that's another topic). 

For now the connection to my OneDrive does not work anymore (and I don't want it to). But there are still encrypted files on my OD. So I tried to decrypt one using your decrypt-file.php script. 
The "decrypt-file.php" is in my home directory along with the "file-to-be-decryped". 

Am I understanding it right that your script gets the master-key from my "nextcloud_data" directory when I set "KEYTYPE" to KEY_MASTER? Because when I try 

`php ./decrypt-file.php /home/jonas/decryption/file-to-be-decrypted.pdf (tried PDF and readme.md)`

I get "File has unknown filename format."-Error. 

I tried to decrypt with the following to settings:

```
    // nextcloud definitions - you can get these values from config/config.php
        define("DATADIRECTORY", "/var/nextcloud_data");
        define("INSTANCEID",    "oca*******");
        define("SECRET",        "secret-from-config.php");

        // custom definitions
        define("DEBUGLEVEL",        DEBUG_DEFAULT);
        define("KEYTYPE",           KEY_USER);
        define("RECOVERY_PASSWORD", "");
        define("USER_NAME",         "Jonas");
        define("USER_PASSWORD",     "my-really-strong-login-password");
```
As well as with:
```
        define("KEYTYPE",           KEY_MASTER);
        define("RECOVERY_PASSWORD", "");
        define("USER_NAME",         "");
        define("USER_PASSWORD",     "");

```

I am still getting the same error. The php script runs under my normal user and has readonly access to the nextcloud_data-Directory, which is still exactly where it should be concerning the nextcloud config.php

For decryption I would prefer to use KEY_USER or KEY_MASTER, because I don't really know where to get the public sharing keys, recovery keys or user keys from (there are so many key files in the nextcloud_data dir with different content form ... I am getting quite confused) 

Hopefully this is just an easy-to-fix error, because me being unable to handle your script right :D

By the way: It was Nextcloud 18.01 that was encrypting the files.  

Anyway: Thanks in advance, stay healthy and have a great eastern. 
Jonas

**Comment by yahesh** [comment]
@JonasOelke Hi, thanks for your issue ticket. I haven't come across encrypted external storage yet. At the moment the script can only decrypt local files that are located within the Nextcloud `DATADIRECTORY` itself. It does this by locating the required files within the directory (namely the master or user private key, the `fileKey` file of the file-to-be-decrypted and the matching `*.shareKey` file of the file-to-be-decrypted).

If I know what the folder structure of such an encrypted external storage in combination with the corresponding local `DATADIRECTORY` looks like then I can probably add the possibility to decrypt those files as well.

**Comment by yahesh** [comment]
@JonasOelke Unfortunately, I haven't heard back from you concerning this topic. I've written the tool [decrypt-all-files.php](https://github.com/syseleven/nextcloud-tools/blob/master/rescue/decrypt-all-files.php) in the meantime, but it still does not support external storages at the moment. If I knew how the file structure looks look for external storages then I could add support for it as well.

**Comment by loetsinn** [comment]
@yahesh Many thx for the good work! I successfully decrypted my files in the user directorys with your [decrypt-all-files.php](https://github.com/syseleven/nextcloud-tools/blob/master/rescue/decrypt-all-files.php)
But I also have files in an external Storage and it would be awesome if you could add support for it.
The structure in my datadir looks like this:

![grafik](https://user-images.githubusercontent.com/16465861/91616705-871dfb80-e986-11ea-9910-8131f7c6cedc.png)

Let me know if this helped you.

**Comment by yahesh** [comment]
@loetsinn I looked into external storage support today and introduced some basic support for it. It's not the nicest of all possibilities, but better than nothing for a first step.

When you add external storages to Nextcloud you have to provide a name to that storage. You can find that name as a folder in `$datadirectory/files_encryption/keys/files/`. What you have to do now is the following:

* You have to mount the external storage somewhere with system tooling. E.g., if you had an external SFTP storage then you could mount that via `sshfs` to somewhere like `/mnt/sshfs`. If you had an external S3 storage then you could mount that via `s3fs` to somewhere like `/mnt/s3fs`.
* You have to look how you named that external storage in Nextcloud. You can see that in the `$datadirectory/files_encryption/keys/files/` folder. Lets say you mounted the SFTP storage as `sftpserver` and and the S3 storage as `s3bucket`.
* You have to set the corresponding defines in the `decrypt-all-files.php` script. Given the example values this would be `define("EXTERNAL_STORAGE_sftpserver", "/mnt/sshfs");` for the external SFTP storage and `define("EXTERNAL_STORAGE_s3bucket", "/mnt/s3fs")` for the external S3 storage

The decrypted files will be stored in corresponding subfolders of the target directory, namely `$targetdir/EXTERNAL_STORAGE_sftpserver` and `$targetdir/EXTERNAL_STORAGE_s3bucket`.

I've tested the new feature with some external folders. Unfortunately, it does currently **not** work for files that have been moved from external storage to the trashbin. I have a rough idea why this might be the case but will have to debug this problem for a bit.

It would be great to hear if this new feature works for you.

**Comment by yahesh** [comment]
Will close this issue for now. Please comment if the introduced support for external storage is not sufficient.
