### ISSUE TITLE
Can not decrypt all files

### ISSUE THREAD

**Issue by pickizme** [syseleven/nextcloud-tools#30]
Hi,

Due an unknown reason `oc_filecache` got corrupted and I was not anymore able to log in. I then tried to decrypt all files via occ. It said all files are decrypted, When I checked it, nothing was changed and all my files were still encrypted.

Using your script, I was able to recover many of my files. It's really a life saver! However, about 20% of the files can not be encrypted in a right way. I also can not determine which files are not decrypted in a right way. 

Is there any way to identify these files or how can I get all my files decrypted?

**Comment by yahesh** [comment]
@pickizme It depends a bit on how old your installation was. You could check if files start with `HBEGIN:` as all files encrypted with "newer" versions (I only know my way around the file structure of Nextcloud starting roughly in 2016) of the Nextcloud Server-Side Encryption contain this header at the beginning of the files.

**Comment by yahesh** [comment]
@pickizme Are you currently running Nextcloud 25? It seems that it has introduced a binary file structure that the decryption script doesn't support yet. I will have to look into it.

**Comment by yahesh** [comment]
@pickizme There has been a major overhaul of this script. Please have a look if it works for you.

**Comment by yahesh** [comment]
Closing this after a quarter without a response.
