### ISSUE TITLE
ERROR: COULD NOT DECRYPT ANY PRIVATE KEY

### ISSUE THREAD

**Issue by DarkShadowxx** [syseleven/nextcloud-tools#31]
Hi, I am running Nextcloud 25 with server side encryption.

I tried to decrypt my files manually, but I always get the following error:

```
www-data@nextcloud:/tmp/nextcloud-tools/rescue$ php8.0 decrypt-all-files.php target/ /mnt/ncdata/private/files/
ERROR: COULD NOT DECRYPT ANY PRIVATE KEY
```

I copied the correct data dir, instance id and secret from the config.php. I also specified both users, Admin and my private user. I tried both current and previous user passwords.
```
        define("DATADIRECTORY", "/mnt/ncdata/");
        define("INSTANCEID",    "oc...");
        define("SECRET",        "ib...");

        define("USER_PASSWORD_private", "test");
        define("USER_PASSWORD_Admin", "test");
```
Here are the available keys:
```
www-data@nextcloud:~$ ls /mnt/ncdata/files_encryption/OC_DEFAULT_MODULE/
master_39xxxxxx.privateKey  master_39xxxxxx.publicKey  pubShare_39xxxxxx.privateKey  pubShare_39xxxxxx.publicKey
```
How can this happen?
I am still able to access my files via the webinterface using my password, so the keys can't be wrong?

**Comment by yahesh** [comment]
@DarkShadowxx Have you only started with Nextcloud 25 or did you use Nextcloud 25 before that? As it seems the newest version has introduced a binary file structure (to reduce the encryption overhead) which is not yet supported by the decryption script.

**Comment by DarkShadowxx** [comment]
I started with Nextcloud 25. 
Please let me know if I can provide any more information.

**Comment by yahesh** [comment]
Ok, then your files are probably already encrypted with the new binary file structure. Will have to look into supporting it before you'll be able to use it.

**Comment by yahesh** [comment]
relates to #32

**Comment by yahesh** [comment]
@DarkShadowxx There has been a major overhaul of this script. Please have a look if it works for you.

**Comment by DarkShadowxx** [comment]
It works now. Thank you.

**Comment by yahesh** [comment]
@DarkShadowxx That's awesome to hear. 💪
