### ISSUE TITLE
Support binary file structure

### ISSUE THREAD

**Issue by yahesh** [syseleven/nextcloud-tools#32]
Nextcloud 25 has introduced a new binary file structure that should be supported.
https://github.com/nextcloud/server/commit/1258caeab7dec7510781ba7b575390459e2e61e5

**Comment by Judicastro** [comment]
Hey

**Comment by yahesh** [comment]
Fixed with https://github.com/syseleven/nextcloud-tools/commit/2480c6170efbcc7693642dc3ff0fdbabff8c1db4.
