### ISSUE TITLE
Script does not start decrypting files/skips single files

### ISSUE THREAD

**Issue by tholbach** [syseleven/nextcloud-tools#34]
First of all, thanks for the great work! I'm sure you have helped a lot of desperate users here! 
I have been nextcloud for about six years now - and I think I have activated encryption about 2 years ago, deactivated it one year ago. Similar as others I had run into problems with the encryiption, ending up with several hundred files being encrypted though encryption had been switched off.

I set up decrypt-all with _DATADIRECTORY_, _INSTANCEID_, _SECRET_, _USER_PASSWORDS_ - I'm not sure if I ever used the recovery feature. 

I've tried decrypt-all in different modes now, but none of this leads to any files being touched. 

When trying to run the script for a single file, I get the following output:

```
DEBUG: debug mode enabled
DEBUG: json = array (
  'key' => 'alongkey'
  'uid' => NULL,
)
DEBUG: header = array (
  'cipher' => 'AES-256-CTR',
  'encoding' => 'base64',
  'keyFormat' => 'hash',
  'oc_encryption_module' => 'OC_DEFAULT_MODULE',
  'signed' => 'false',
)
DEBUG: meta = array (
  'encrypted' => 'anotherlongstring (4360 bytes)',
  'iv' => 'anotherverylongstring',
  'signature' => 'heeeereeetoo',
)
DEBUG: loaded private key for master_920d056e
DEBUG: json = array (
  'key' => 'somethingverylong'
  'uid' => NULL,
)
DEBUG: header = array (
  'cipher' => 'AES-256-CTR',
  'encoding' => 'base64',
  'keyFormat' => 'hash',
  'oc_encryption_module' => 'OC_DEFAULT_MODULE',
  'signed' => 'false',
)
DEBUG: meta = array (
  'encrypted' => 'abc123 (4364 bytes)',
  'iv' => '321abc',
  'signature' => 'abc123123',
)
DEBUG: loaded private key for pubShare_920d056e
DEBUG: filename = /storage//nextcloud/username/files/Rezepte/Birnenkompott/full.jpg
DEBUG: target = /storage/nextcloud_decrypted_files/username/files/Rezepte/Birnenkompott/full.jpg
DEBUG: skipping this file...
```

If I run the script for nextcloud's whole data directory, I just initially get the following log in debug mode, but after this nothing really happens (for hours). 

```DEBUG: debug mode enabled
DEBUG: json = array (
  'key' => 'anotherlongkey'
  'uid' => NULL,
)
DEBUG: header = array (
  'cipher' => 'AES-256-CTR',
  'encoding' => 'base64',
  'keyFormat' => 'hash',
  'oc_encryption_module' => 'OC_DEFAULT_MODULE',
  'signed' => 'false',
)
DEBUG: meta = array (
  'encrypted' => 'yetanotherlongkey (4360 bytes)',
  'iv' => '6bed5c6ecc44533b87da4a70ba3677fc',
  'signature' => 'f06b0bf6de8f9ba9ac1555da9acb4487647656d0e26a0cdf97c60f1a4f3cdc11',
)
DEBUG: loaded private key for master_920d056e
DEBUG: json = array (
  'key' => 'averylongstringhere'
  'uid' => NULL,
)
DEBUG: header = array (
  'cipher' => 'AES-256-CTR',
  'encoding' => 'base64',
  'keyFormat' => 'hash',
  'oc_encryption_module' => 'OC_DEFAULT_MODULE',
  'signed' => 'false',
)
DEBUG: meta = array (
  'encrypted' => 'abc123abc123',
  'iv' => 'abc123abc123',
  'signature' => 'abc123abc123',
)
DEBUG: loaded private key for pubShare_920d056e
DEBUG: debug mode enabled
DEBUG: json = array (
  'key' => 'abc123abc123',
  'uid' => NULL,
)
DEBUG: header = array (
  'cipher' => 'AES-256-CTR',
  'encoding' => 'base64',
  'keyFormat' => 'hash',
  'oc_encryption_module' => 'OC_DEFAULT_MODULE',
  'signed' => 'false',
)
DEBUG: meta = array (
  'encrypted' => 'abc123abc123',
  'iv' => 'abc123abc123',
  'signature' => 'abc123abc123',
)
DEBUG: loaded private key for master_920d056e
DEBUG: json = array (
  'key' => 'abc123abc123'.
  'uid' => NULL,
)
DEBUG: header = array (
  'cipher' => 'AES-256-CTR',
  'encoding' => 'base64',
  'keyFormat' => 'hash',
  'oc_encryption_module' => 'OC_DEFAULT_MODULE',
  'signed' => 'false',
)
DEBUG: meta = array (
  'encrypted' => '74375a69523848575a72612f5a3146714d35734479415432352b48416b39446b...6b6f4c6467513934544248564e4b69575843645668506970523433755771513d (4364 bytes)',
  'iv' => '286dcb2d30441c44cff937323e05afa4',
  'signature' => '5a62e976bbc94f10c291d0da703c6e1ba8bf5753e549a783c9126bea95cf408b',
)
DEBUG: loaded private key for pubShare_920d056e
```

Thanks for your help!

**Comment by yahesh** [comment]
@tholbach What seems strange to me is that the `filename` contains a double slash:

`/storage//nextcloud/username/files/Rezepte/Birnenkompott/full.jpg` which might skew the regex which checks if the filename has a known format. Could you please check what exactly you have entered as the `DATADIRECTORY`?

**Comment by tholbach** [comment]
@yahesh , thanks for your quick help!

- single file decryption: Removing the double slash solved the problem.
- all files decryption: I was using a directory instead of its symlink specified in the Nextcloud configuration. Changing this solved the problem.

**Comment by yahesh** [comment]
@tholbach I'm happy that this worked out for you now. I'd like to reopen this ticket, though. I see at least one improvement of for the script at them moment: Instead of just taking filenames as they are, the script could throw them through `realpath()` to clean them up. This would probably improve path matching.

Unfortunately, I don't really understand what your problem with the symlink was. It would be great if you could elaborate on that a bit more. Future users might run into the same problem.

**Comment by yahesh** [comment]
Moving the improvement over to https://github.com/syseleven/nextcloud-tools/issues/37.
