### ISSUE TITLE
Copy or upload decrypted files

### ISSUE THREAD

**Issue by tholbach** [syseleven/nextcloud-tools#36]
I started to use Nextcloud's server side encryption longer time ago, ran into problems and deactivated the encryption. Thousands of files were still encrypted. With the help of decrypt all files I was able to decrypt the related files. Thank you!
I now want to use these files back in nextcloud. 

My question: 
Should the decrypted files be reuploaded via the client/nextcloud website (and overwrite existing files) or can I simply copy them on the filesystem (and overwrite existing files)? In other words: Does Nextcloud hold any information in its db that needs to be updated within the process? Can you recommend any best practice?

Thanks for your help!

**Comment by yahesh** [comment]
@tholbach I'm happy that the script worked out for you. :)

The easiest way is probably to reupload the files. There are two reasons:
1.) The files relating the encryption are still lying around. This could hint future updates of Nextcloud to assume that the files are still encrypted. I personally wouldn't risk it.
2.) There is an information stored in the database that tells Nextcloud which files are presumably encrypted. This would have to be cleaned up before replacing the encrypted files with unencrypted files (have a look at the `encrypted` field in the `oc_filecache` table of the Nextcloud database).

**Comment by tholbach** [comment]
As always, thanks a lot!
