### ISSUE TITLE
extend support for file decryption to files from e.g. Collectives

### ISSUE THREAD

**Issue by KiaraGrouwstra** [syseleven/nextcloud-tools#38]
i'm dealing with a file that ended up not decrypting (i.e., shows as garbage offline and online) that doesn't match the present regexes used in this repo.
the path currently takes the shape `/var/www/nextcloud/data/appdata_ocb0yb2ks9ew/collectives/3/my_folder/my_file.odt`, i.e. a file shared thru nextcloud [collectives](https://github.com/nextcloud/collectives).
i imagine the ability to store files might also not be exclusive to that particular app, i.e. this may be relevant also for other for other files in `data/appdata_*`.

it would be nice if decrypting support here could be extended to include such app-managed files.
for what it's worth, the file in question here still seems to use encryption keys stored using the traditional pattern, in this case `./data/my_user/files_encryption/keys/files/my_file.odt`.

**Comment by yahesh** [comment]
@KiaraGrouwstra I haven't worked with the collectives App yet and will have to have a look into that. Given that the key for that file resides in a user's folder I'd assume that there might be a copy of that file as well? Otherwise, there must probably be some mapping info in the database.

**Comment by yahesh** [comment]
@KiaraGrouwstra Are the keys located under a specific user called `collectives`?

https://github.com/nextcloud/collectives/blob/main/lib/Fs/UserFolderHelper.php#L52-L75

**Comment by KiaraGrouwstra** [comment]
> @KiaraGrouwstra Are the keys located under a specific user called `collectives`?
the user name was just that of the user who created the content in the Collectives app, not a user called `collectives`.
i believe our user had not used the setting to have a copy of the files stored in their personal space, and in fact their user space contained no such copy, only the keys.

i imagine you're right mapping must be done from the db.

**Comment by yahesh** [comment]
I see. Sounds as if I'll have to build up a test infrastructure to see in person how that App behaves.

**Comment by yahesh** [comment]
I don't assume that there will be the possibility to support any `data/appdata_*` folder as each application decides for itself how and where to store which data. This would be, if successful, additional support for this specific App.

**Comment by yahesh** [comment]
@KiaraGrouwstra Hi there! Could you give me a hint how you enabled the server-side encryption for the Collectives app? There doesn't seem to be any configuration and when I move an encrypted file into the collective then it gets decrypted on the fly.

**Comment by KiaraGrouwstra** [comment]
interesting, thank you.
we made no active effort to explicitly enable encryption for the Collectives app.
i'm not sure what went wrong then, but then i'm also no longer sure if there's anything actionable for this repo there.

**Comment by yahesh** [comment]
@KiaraGrouwstra If I understand correctly, then the Collectives app doesn't support encryption yet (see https://github.com/nextcloud/collectives/issues/285). The issue might come from a previous bug in Nextcloud itself, where files where not decrypted properly when being moved from encrypted storage to unencrypted storage (see https://github.com/nextcloud/server/pull/35894).

If that's really the source of the issue then I don't see a generic solution for this problem. It would probably be easiest to identify the files that cannot be decrypted and copy them into their original location. Then the rescue script would be able to find the corresponding keys as usual.
